# Step 6: Deploy to Elastic Beanstalk
- name: Deploy to EB
  uses: einaregilsson/beanstalk-deploy@v20
  with:
    application_name: basicServer          # Your EB Application Name
    environment_name: basicServer-env      # Your EB Environment Name
    region: ap-northeast-3                 # Change to your AWS region
    version_label: ${{ github.sha }}
    deployment_package: app.zip            # <-- Point to your zipped app
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
